name: Deploy Theme
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '10' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: | 
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install yarn -g
      - run: yarn
      - name: Build and Test theme
        run: yarn test && yarn zip
      - name: Setup Deploy
        working-directory: ./deploy
        run: yarn
      - name: 'Deploy Ghost Theme'
        run: node deploy/index.js
        env:
          url: ${{ secrets.GHOST_ADMIN_API_URL }}
          key: ${{ secrets.GHOST_ADMIN_API_KEY }}